spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: febs-auth-tjdk
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        boot:
          actuate:
            endpoint:
              EndpointId: error

